name: ci

on:
  push:
  pull_request:

jobs:
  Ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: |
          mkdir build && cd build
          cmake ..
          cmake --build .