name: ci

on:
  push:
  pull_request:

jobs:
  Ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        # sudo apt-get remove -y clang-13
        # wget https://apt.llvm.org/llvm.sh
        # chmod +x llvm.sh
        # sudo ./llvm.sh 15 all
        # sudo apt-get update
        # sudo pip install lit

    - name: Build
      run: |
          mkdir build && cd build
          mkdir src && cd src
          mkdir tool && cd tool
          touch a
          chmod +x a
          
          # cmake ..
          # cmake --build .
          pwd
          echo $PWD
          # export PATH="$PWD/src/tool:$PATH"
          export PATH="$PWD:$PATH"
          echo $PATH
          a
          
    - name: Test
      run: |
          # cd build
          # lit -v test/
