name: ci

on:
  push:
  pull_request:

jobs:
  Ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get remove -y clang-13
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15 all
        sudo apt-get update
        sudo pip install lit

    - name: Build
      run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
